Repository whyboris/Video-Hub-App, pull requests merged in 2018-12, with the labels that each got.

#2 Thumbnail Improvements
  main-globals.ts
  main-support.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/filmstrip/filmstrip.component.html
  src/app/components/home/filmstrip/filmstrip.component.scss
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
  src/app/components/pipes/file-size.pipe.ts
  src/assets/demo-content.ts
Labels: enhancement

#8 Allow for an input folder relative to the vha file location
  main-support.ts
  main.ts
Labels: bug, enhancement

#20 Translation system for any language
  README.md
  main.ts
  package.json
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/components/common/filters.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/common/settings-object.interface.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/resfilter/resfilter.component.ts
  src/app/components/home/tags/tags.component.html
  src/app/components/home/tags/tags.component.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
  tslint.json
Labels: enhancement, feature request, ✏️ ready for review

#28 Add shift click to exclude tags!
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
Labels: feature request, ✏️ ready for review

#33 Upgrade electron to v4.0.0 and implement Dirent objects for file listing!
  main-support.ts
  package.json
Labels: enhancement, ✏️ ready for review

#30 Replace fluent-ffmpeg with ffprobe exec command!
  main-support.ts
  main.ts
  package.json
Labels: enhancement, ✏️ ready for review

#32 Implement prompt for root folder when folder doesn’t exist!
  main.ts
  src/app/components/home/home.component.ts
Labels: bug, enhancement, ✏️ ready for review

#22 Implement video previews!
  main-support.ts
  main.ts
  package.json
  src/app/app.module.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.scss
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
Labels: feature request, ✏️ ready for review

#36 Fix ignoring folders!
  main-support.ts
Labels: bug, ✏️ ready for review

#40 Folder-only view
  .vscode/extensions.json
  src/app/components/common/settings-buttons.ts
  src/app/components/home/file/file.component.html
  src/app/components/home/file/file.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/pipes/folder-view.pipe.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: ✏️ ready for review

#41 Remember window size and position
  main.ts
  src/app/components/common/app-state.ts
  src/app/components/common/import.interface.ts
  src/app/components/common/savable-properties.interface.ts
  src/app/components/common/settings-buttons.interface.ts
  src/app/components/common/settings-object.interface.ts
Labels: ✏️ ready for review

#42 fix first run bug
  main.ts
  src/app/components/home/home.component.ts
Labels: ✏️ ready for review

#43 Better organized settings menu
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/settings.scss
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: ✏️ ready for review

#44 New filmstrip
  main-filenames.ts
  main-misc.ts
  main-support.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/filmstrip/filmstrip.component.html
  src/app/components/home/filmstrip/filmstrip.component.scss
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/tags/tags.component.ts
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: ✏️ ready for review

#49 Convert arrays to objects!
  main-support.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/tags/tags.service.ts
  src/app/components/pipes/file-search.pipe.ts
  src/app/components/pipes/folder-view.pipe.ts
  src/app/components/pipes/magic-search.pipe.ts
  src/app/components/pipes/resolution-filter.pipe.ts
  src/app/components/pipes/similarity.pipe.ts
  src/app/components/pipes/word-frequency.pipe.ts
  src/assets/demo-content.ts
Labels: enhancement, ✏️ ready for review

#52 Statistics menu
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/home/statistics/statistics.component.html
  src/app/components/home/statistics/statistics.component.scss
  src/app/components/home/statistics/statistics.component.ts
  src/app/components/pipes/file-size.pipe.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: ✏️ ready for review

#48 Filmstrip bugfixes
  main-support.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.scss
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
  src/assets/demo-content.ts
Labels: ✏️ ready for review

#54 4K filter now works
  main-support.ts
  src/app/components/home/file/file.component.scss
  src/app/components/home/home.component.ts
  src/app/components/home/resfilter/resfilter.component.ts
  src/app/components/pipes/resolution-filter.pipe.ts
  src/app/components/pipes/resolution-filter.service.ts
Labels: ✏️ ready for review

#55 Variable number of screenshots option
  main-globals.ts
  main-support.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/common/import.interface.ts
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/thumbnail/preview.component.ts
  src/app/components/home/wizard.scss
  src/app/components/pipes/folder-view.pipe.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: ✏️ ready for review

#56 Fix readme typo
  README.md
Labels: ✏️ ready for review
