Repository whyboris/Video-Hub-App, pull requests merged in 2019-05, with the labels that each got.

#171 Minor fixes
  main-misc.ts
  package.json
  src/app/components/home/clip/clip.component.scss
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/manual-tags/add-tag.component.scss
  src/app/components/home/manual-tags/add-tag.component.ts
  src/app/components/home/meta/meta.component.html
  src/app/components/home/meta/meta.component.scss
  src/app/components/home/settings.scss
  src/app/components/home/statistics/statistics.component.html
  src/app/components/home/statistics/statistics.component.scss
  src/app/components/home/statistics/statistics.component.ts
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
  src/app/components/pipes/sorting.pipe.ts
  src/app/i18n/en.ts
Labels: 2.0.0, ✏️ ready for review

#172 Update ngx-virtual-scroller
  package.json
  src/app/components/home/details/details.component.scss
  src/app/components/home/filmstrip/filmstrip.component.scss
  src/app/components/home/home.component.html
Labels: 2.0.0, ✏️ ready for review

#174 Similar videos tab
  package.json
  src/app/components/common/animations.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.scss
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/details/details.component.scss
  src/app/components/home/filmstrip/filmstrip.component.scss
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
  src/app/components/pipes/similarity.pipe.ts
  src/app/i18n/en.ts
Labels: 2.0.0, enhancement, ✏️ ready for review

#176 Update Electron to 5.0.1
  .gitignore
  README.md
  angular.json
  main.ts
  package-lock.json
  package.json
  src/app/components/pipes/similarity.service.ts
  tslint.json
Labels: 2.0.0, ✏️ ready for review

#164 Add sheet icon to thumbnails
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.scss
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
Labels: 2.0.0, ✏️ ready for review

#181 Actually quit the app
  main.ts
Labels: bug, ✏️ ready for review
