Repository whyboris/Video-Hub-App, pull requests merged in 2019-07, with the labels that each got.

#197 Video Hub App 2
  electron-builder.json
  main.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
Labels: 2.0.0, enhancement

#199 All extraction code in its own file and uses Promise
  .gitignore
  main-extract.ts
  main-globals.ts
  main-support.ts
  main.ts
  package.json
  src/app/components/common/import.interface.ts
  src/app/components/common/wizard-options.interface.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/wizard.scss
  src/app/i18n/en.ts
Labels: 2.0.0, ✏️ ready for review

#200 Tag autocomplete
  src/app/app.module.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/donut/donut.component.scss
  src/app/components/home/buttons.scss
  src/app/components/home/details/details.component.html
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
  src/app/components/home/manual-tags/add-tag.component.html
  src/app/components/home/manual-tags/add-tag.component.scss
  src/app/components/home/manual-tags/add-tag.component.ts
  src/app/components/home/manual-tags/manual-tags.service.ts
  src/app/components/home/manual-tags/view-tags.component.html
  src/app/components/home/manual-tags/view-tags.component.scss
  src/app/components/home/manual-tags/view-tags.component.ts
  src/app/components/home/meta/meta.component.html
  src/app/components/home/meta/meta.component.ts
  src/app/components/home/resolution.scss
  src/app/components/home/search.scss
  src/app/components/home/settings.scss
  src/app/components/home/sheet/sheet.component.ts
  src/app/components/home/tags/tag-display.pipe.ts
  src/app/components/home/tags/tag-match.pipe.ts
  src/app/components/home/tags/tags.component.scss
  src/app/components/home/tags/tags.component.ts
  src/app/components/home/variables.scss
  src/app/components/pipes/manual-tags-sort.pipe.ts
  src/app/i18n/en.ts
Labels: 2.0.0, enhancement, feature request, ✏️ ready for review

#201 Fix EMFILE: too many open files bug
  main-support.ts
Labels: 2.0.0, bug

#195 Add translation process automation
  src/app/i18n/translate.sh
Labels: 2.0.0, enhancement

#203 Handle folders with spaces
  main.ts
Labels: 2.0.0

#202 Version bump
  README.md
  package-lock.json
  package.json
Labels: 2.0.0, stalled

#208 Fix and also disable checkAllScreensExist
  main-extract.ts
Labels: 2.0.0, discussion, help wanted, ✏️ ready for review

#209 mute works across all clip view variations
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.ts
Labels: 2.0.0, enhancement, ✏️ ready for review

#210 thumbnail autoadvance & setting toggle & refactor
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.ts
  src/app/i18n/en.ts
Labels: 2.0.0, ✏️ ready for review

#212 Duration filter improvement
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/slider-filter/slider-filter.component.html
  src/app/components/home/slider-filter/slider-filter.component.scss
  src/app/components/home/slider-filter/slider-filter.component.ts
  src/app/components/home/statistics/statistics.component.html
  src/app/components/pipes/length.pipe.ts
  src/app/components/pipes/sorting.pipe.ts
  src/app/components/pipes/star-filter.service.ts
Labels: 2.0.0, enhancement, ✏️ ready for review

#213 Similar video improvements
  src/app/components/home/home.component.html
  src/app/components/home/layout.scss
Labels: 2.0.0, enhancement, ✏️ ready for review

#215 Rescan refactor
  .gitignore
  README.md
  main-globals.ts
  main-rescan.ts
  main-support.ts
  main.ts
  package.json
Labels: 2.0.0, ✏️ ready for review

#217 Settings cleanup
  main.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/meta/meta.component.html
  src/app/components/home/sheet/sheet.component.ts
  src/app/components/home/thumbnail/preview.component.ts
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/pt_br.ts
  src/app/i18n/ru.ts
Labels: 2.0.0, ✏️ ready for review

#211 OS X - dark mode
  main.ts
  package-lock.json
  package.json
  src/app/components/home/home.component.ts
Labels: 2.0.0, ✏️ ready for review

#220 code for OS dark mode works on Mac, does not crash on other OS
  main.ts
  package-lock.json
Labels: 2.0.0

#222 CTRL + F works again
  src/app/components/home/home.component.ts
Labels: 2.0.0

#224 Rescan fixes
  main-extract.ts
  main-rescan.ts
  main-support.ts
  main.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/i18n/en.ts
Labels: 2.0.0, ✏️ ready for review

#225 better stats & re-scan improvements
  main-extract.ts
  main.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/statistics/statistics.component.html
  src/app/components/home/statistics/statistics.component.scss
  src/app/components/home/statistics/statistics.component.ts
  src/app/components/pipes/length.pipe.ts
  src/app/i18n/en.ts
Labels: 2.0.0, ⛑️ WIP

#226 no clips extracted message when appropriate
  src/app/components/home/home.component.html
  src/app/components/home/layout.scss
  src/app/i18n/en.ts
Labels: 2.0.0

#228 Rescan buttons added to toolbar
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/i18n/en.ts
Labels: 2.0.0

#229 Compact View!
  src/app/components/common/animations.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/buttons.scss
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
  src/app/components/home/search.scss
  src/app/components/home/settings.scss
  src/app/components/home/sheet/sheet.component.scss
  src/app/components/home/statistics/statistics.component.scss
  src/app/components/home/tags/tags.component.html
  src/app/components/home/tags/tags.component.scss
  src/app/components/home/tags/tags.component.ts
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/thumbnail/preview.component.ts
  src/app/components/home/top-buttons.scss
  src/app/components/home/top/top.component.scss
  src/app/components/home/variables.scss
  src/app/components/home/wizard-button.scss
  src/app/components/home/wizard.scss
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/pt_br.ts
  src/app/i18n/ru.ts
  src/index.html
Labels: 2.0.0

#230 Cleaning css
  src/app/components/common/colors.ts
  src/app/components/common/filters.ts
  src/app/components/home/buttons.scss
  src/app/components/home/clip/clip.component.scss
  src/app/components/home/details/details.component.scss
  src/app/components/home/gallery.scss
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
  src/app/components/home/manual-tags/view-tags.component.html
  src/app/components/home/manual-tags/view-tags.component.scss
  src/app/components/home/meta/meta.component.scss
  src/app/components/home/search-input.scss
  src/app/components/home/search.scss
  src/app/components/home/settings.scss
  src/app/components/home/sheet/sheet.component.scss
  src/app/components/home/slider-filter/slider-filter.component.scss
  src/app/components/home/tags/tag-display.pipe.ts
  src/app/components/home/tags/tags.component.scss
  src/app/components/home/tags/tags.component.ts
  src/app/components/home/thumbnail/preview.component.scss
  src/app/components/home/top-buttons.scss
  src/app/components/home/top/top.component.scss
  src/app/components/home/variables.scss
  src/app/components/home/wizard.scss
Labels: 2.0.0

#232 More cleaning
  demo/index.html
  src/app/components/fonts/icons.scss
  src/app/components/gallery.scss
  src/app/components/home.component.html
  src/app/components/home.component.ts
  src/app/components/meta/meta.component.html
  src/app/components/meta/meta.component.scss
  src/app/components/rightclick.scss
  src/app/components/sheet/sheet.component.html
  src/app/components/sheet/sheet.component.scss
  src/app/components/tags-manual/add-tag.component.html
  src/app/components/tags-manual/add-tag.component.scss
  src/app/components/tags-manual/add-tag.component.ts
  src/app/components/top/top.component.scss
  src/app/components/views/details/details.component.scss
  src/app/components/views/file/file.component.html
  src/app/components/views/file/file.component.scss
  src/app/i18n/en.ts
Labels: 2.0.0

#233 Cleaning still
  src/app/components/common/settings-buttons.ts
  src/app/components/home.component.html
  src/app/components/home.component.ts
  src/app/components/meta/meta.component.ts
  src/app/components/pipes/file-search.pipe.ts
  src/app/components/pipes/magic-search.pipe.ts
  src/app/components/pipes/manual-tags-sort.pipe.ts
  src/app/components/pipes/sorting.pipe.ts
  src/app/components/search.scss
  src/app/components/sheet/sheet.component.ts
  src/app/components/views/full/full.component.ts
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/pt_br.ts
  src/app/i18n/ru.ts
Labels: 2.0.0
