Repository whyboris/Video-Hub-App, pull requests merged in 2019-01, with the labels that each got.

#59 Fix tag replace regex to only replace full words!
  src/app/components/home/tags/tags.service.ts
  src/app/components/pipes/word-frequency.service.ts
Labels: bug, enhancement, ✏️ ready for review

#64 Add support for importing new files, and verifying thumbnails!
  main-support.ts
  main.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.ts
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: enhancement, feature request, ✏️ ready for review

#68 remove numberOfVidsIn method
  main-support.ts
  main.ts
Labels: ✏️ ready for review

#70 Optimise output resolutions for scaling!
  main-support.ts
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
Labels: enhancement, performance, regression, ✏️ ready for review

#78 auto detect language on first start
  main.ts
  src/app/components/common/app-state.ts
  src/app/components/common/settings-object.interface.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
Labels: ✏️ ready for review

#79 handle Mac cmd + Q not saving setting bug
  main.ts
Labels: ✏️ ready for review

#77 progress bar in taskbar
  main-globals.ts
  main-support.ts
  main.ts
Labels: ✏️ ready for review

#74 Add a script to jump start new translations!
  src/app/i18n/fr.ts
  src/app/i18n/translate.sh
Labels: ✏️ ready for review

#81 Add autoplay option for video preview clips!
  src/app/components/common/settings-buttons.ts
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/home.component.html
  src/app/i18n/en.ts
  src/app/i18n/ru.ts
Labels: enhancement, feature request, ✏️ ready for review

#82 Instructions for adding a language
  README.md
  src/app/components/common/app-state.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/i18n/README.md
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/ru.ts
Labels: ✏️ ready for review

#83 Fix for corrupt metadata in files!
  main-support.ts
Labels: bug, ✏️ ready for review

#88 Default screenshot size bug fix!
  main-globals.ts
  src/app/components/home/home.component.ts
Labels: bug, ✏️ ready for review

#89 Organising vha folder!
  main-support.ts
  main.ts
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/sheet/sheet.component.ts
  src/app/components/home/thumbnail/preview.component.ts
Labels: breaking, enhancement, ✏️ ready for review

#85 Add extended word cloud option!
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/pipes/word-frequency.pipe.ts
  src/app/components/pipes/word-frequency.service.ts
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/ru.ts
Labels: enhancement, feature request, ✏️ ready for review

#84 Update translate.sh
  src/app/i18n/translate.sh
Labels: bug, ✏️ ready for review

#96 Ignore files beginning with ‘.’ And ‘_’!
  main-support.ts
Labels: bug, enhancement, ✏️ ready for review

#94 Fix when space in path to vha file!
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/thumbnail/preview.component.ts
Labels: bug, ✏️ ready for review

#90 Converted ResFilter into a generic SliderFilter!
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/home/resolution.scss
  src/app/components/home/slider-filter/slider-filter.component.html
  src/app/components/home/slider-filter/slider-filter.component.scss
  src/app/components/home/slider-filter/slider-filter.component.ts
Labels: enhancement, ✏️ ready for review

#98 Use subfile hash again!
  main-support.ts
Labels: breaking, enhancement, ✏️ ready for review

#87 fullView - view every screenshot of every video at once in one view!
  src/app/app.module.ts
  src/app/components/common/app-state.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/full/full.component.html
  src/app/components/home/full/full.component.scss
  src/app/components/home/full/full.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
  src/app/i18n/en.ts
Labels: enhancement, ✏️ ready for review

#104 Manual tags
  src/app/app.module.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/manual-tags/add-tag.component.html
  src/app/components/home/manual-tags/add-tag.component.scss
  src/app/components/home/manual-tags/add-tag.component.ts
  src/app/components/home/manual-tags/manual-tags.service.ts
  src/app/components/home/manual-tags/view-tags.component.html
  src/app/components/home/manual-tags/view-tags.component.scss
  src/app/components/home/manual-tags/view-tags.component.ts
  src/app/components/home/tags/tag-match.pipe.ts
  src/app/components/home/tags/tags-save.service.ts
  src/app/components/home/tags/tags.component.ts
  src/app/components/home/tags/tags.service.ts
Labels: enhancement, ✏️ ready for review

#105 Star rating implemented
  main-support.ts
  src/app/app.module.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/details/details.component.scss
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/pipes/folder-view.pipe.ts
  src/app/components/pipes/star-filter.pipe.ts
  src/app/components/pipes/star-filter.service.ts
  src/app/i18n/en.ts
Labels: enhancement, ✏️ ready for review

#106 Tag tray - first draft
  src/app/components/common/settings-buttons.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/home.component.html
  src/app/components/home/layout.scss
  src/app/components/home/manual-tags/view-tags.component.html
  src/app/components/home/manual-tags/view-tags.component.scss
  src/app/i18n/en.ts
Labels: ✏️ ready for review

#107 Tag tray updates
  src/app/app.module.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/layout.scss
  src/app/components/home/manual-tags/add-tag.component.html
  src/app/components/home/manual-tags/manual-tags.service.ts
  src/app/components/home/manual-tags/view-tags.component.html
  src/app/components/home/manual-tags/view-tags.component.scss
  src/app/components/home/manual-tags/view-tags.component.ts
  src/app/components/pipes/manual-tags-sort.pipe.ts
  src/app/i18n/en.ts
Labels: enhancement, ✏️ ready for review

#109 Corrupt video detection
  main-support.ts
  main.ts
Labels: bug, regression, ✏️ ready for review

#111 Input & pipe cleanup
  main-support.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/clip/clip.component.html
  src/app/components/home/clip/clip.component.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/file/file.component.html
  src/app/components/home/file/file.component.scss
  src/app/components/home/file/file.component.ts
  src/app/components/home/filmstrip/filmstrip.component.html
  src/app/components/home/filmstrip/filmstrip.component.ts
  src/app/components/home/full/full.component.html
  src/app/components/home/full/full.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/sheet/sheet.component.html
  src/app/components/home/sheet/sheet.component.scss
  src/app/components/home/sheet/sheet.component.ts
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/home/thumbnail/preview.component.ts
  src/app/components/pipes/folder-view.pipe.ts
Labels: ✏️ ready for review

#93 Added version to vha file! Bumped to v2.0.0a!
  main-globals.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/home.component.ts
Labels: enhancement, ✏️ ready for review

#112 Video length filter-ish
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/slider-filter/slider-filter.component.html
  src/app/components/home/slider-filter/slider-filter.component.scss
  src/app/components/home/slider-filter/slider-filter.component.ts
  src/app/components/pipes/length-filter.pipe.ts
  src/app/components/pipes/length.pipe.ts
  src/app/components/pipes/wrapper.pipe.ts
Labels: feature request, ⛑️ WIP

#116 Custom tag filters, bug fixes and folder tags - oh my! 🦁 🐯 🐻 😱
  src/app/app.module.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/details/details.component.scss
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/manual-tags/add-tag.component.scss
  src/app/components/home/manual-tags/view-tags.component.html
  src/app/components/home/manual-tags/view-tags.component.scss
  src/app/components/home/manual-tags/view-tags.component.ts
  src/app/components/home/tags/autotags.service.ts
  src/app/components/home/tags/tag-filter.pipe.ts
  src/app/components/home/tags/tag-match.pipe.ts
  src/app/components/home/tags/tags.component.ts
  src/app/components/home/tags/tags.service.ts
  src/app/components/pipes/file-search.pipe.ts
  src/app/components/pipes/word-frequency.pipe.ts
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/ru.ts
Labels: bug, enhancement, feature request, ✏️ ready for review

#120 duration filter has its own toggle
  src/app/components/home/details/details.component.html
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/slider-filter/slider-filter.component.html
  src/app/components/home/slider-filter/slider-filter.component.scss
  src/app/components/home/slider-filter/slider-filter.component.ts
  src/app/components/pipes/length.pipe.ts
  src/app/components/pipes/wrapper.pipe.ts
Labels: ✏️ ready for review

#124 Implement modified time sorting!
  main-support.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/home.component.html
  src/app/components/pipes/folder-view.pipe.ts
  src/app/components/pipes/sorting.pipe.ts
  src/app/i18n/en.ts
Labels: feature request, ✏️ ready for review

#127 Fix restoring number of screenshots!
  main.ts
Labels: bug, regression, ✏️ ready for review

#128 THANK YOU FFMPEG! <3
  main-support.ts
Labels: bug, enhancement, regression, ✏️ ready for review

#130 Implement debug mode for logging!
  main-globals.ts
  main-support.ts
  main.ts
  package.json
Labels: bug, feature request, regression, ✏️ ready for review

#137 better menu labels and organization
  src/app/components/common/animations.ts
  src/app/components/common/settings-buttons.interface.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/clip/clip.component.html
  src/app/components/home/details/details.component.html
  src/app/components/home/file/file.component.html
  src/app/components/home/filmstrip/filmstrip.component.html
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/search.scss
  src/app/components/home/settings.scss
  src/app/components/home/statistics/statistics.component.html
  src/app/components/home/statistics/statistics.component.scss
  src/app/components/home/thumbnail/preview.component.html
  src/app/components/pipes/length.pipe.ts
  src/app/i18n/en.ts
  src/app/i18n/fr.ts
  src/app/i18n/ru.ts
Labels: enhancement, ✏️ ready for review
