Repository whyboris/Video-Hub-App, pull requests merged in 2019-02, with the labels that each got.

#138 Better thumbnail number selection
  main-globals.ts
  main-support.ts
  main.ts
  postcss.config.js
  src/app/components/common/final-object.interface.ts
  src/app/components/common/import.interface.ts
  src/app/components/common/wizard-options.interface.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/settings.scss
  src/app/components/home/wizard.scss
Labels: enhancement, ✏️ ready for review

#140 Number of times played, year meta tag, & star sorting options
  main-support.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/home/details/details.component.html
  src/app/components/home/details/details.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/meta/meta.component.html
  src/app/components/home/meta/meta.component.scss
  src/app/components/home/meta/meta.component.ts
  src/app/components/home/settings.scss
  src/app/components/home/sheet/sheet.component.html
  src/app/components/home/sheet/sheet.component.ts
  src/app/components/home/statistics/statistics.component.html
  src/app/components/home/statistics/statistics.component.scss
  src/app/components/home/statistics/statistics.component.ts
  src/app/components/pipes/folder-view.pipe.ts
  src/app/components/pipes/sorting.pipe.ts
  src/app/i18n/en.ts
Labels: enhancement, ✏️ ready for review

#142 sort options toggles
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/home/settings.scss
  src/app/i18n/en.ts
Labels: enhancement

#146 do not open clicked file when root folder not live
  .vscode/extensions.json
  main.ts
  src/app/components/home/home.component.ts
Labels: ✏️ ready for review

#147 insert temp fields after writing file
  main.ts
Labels: ✏️ ready for review

#148 better default active buttons, reorder buttons
  main.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.ts
  src/app/i18n/en.ts
Labels: ✏️ ready for review

#149 clear filter when hiding
  src/app/components/common/filters.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
Labels: ✏️ ready for review

#150 fix resolution and duration filter kerfuffle
  src/app/components/home/home.component.html
Labels: ✏️ ready for review

#152 Remember zoom level
  src/app/components/common/app-state.ts
  src/app/components/home/buttons.scss
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/sheet/sheet.component.html
  src/app/components/home/sheet/sheet.component.scss
  src/app/components/home/slider-filter/slider-filter.component.html
  src/app/components/home/slider-filter/slider-filter.component.scss
  src/app/components/home/slider-filter/slider-filter.component.ts
Labels: ✏️ ready for review

#153 Five stars
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/home/meta/meta.component.html
  src/app/components/home/meta/meta.component.scss
  src/app/components/home/resolution.scss
  src/app/components/pipes/star-filter.service.ts
Labels: ✏️ ready for review

#154 Add vha file backup when saving!
  main-support.ts
Labels: 2.0.0, enhancement, feature request

#155 Implement regenerating library metadata!
  main-support.ts
  main.ts
  src/app/components/common/final-object.interface.ts
  src/app/components/common/settings-buttons.ts
  src/app/components/home/home.component.ts
  src/app/i18n/en.ts
Labels: 2.0.0, enhancement, feature request, performance
